apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ibraheem-new-cert  # Update to your desired certificate name
  namespace: sock-shop
spec:
  secretName: alade-nginx-secret  # Update to your desired secret name
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  commonName: www.ibraheem-alade.me
  dnsNames:
  - ibraheem-alade.me
  - www.ibraheem-alade.me
