apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ibraheem-certificate
  namespace: sock-shop
spec:
  secretName: letsencrypt-nginx-private-key
  issuerRef: 
    name: letsencrypt-nginx
    kind: ClusterIssuer
  commonName: www.ibraheem-alade.me
  dnsNames:
  - www.ibraheem-alade.me