apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-nginx
  namespace: sock-shop
spec:
  acme:
    email: bauerautocad@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: alade-new-nginx  # This secret will store the ACME account's private key
    solvers:
      - http01:
          ingress:
            class: nginx
